import { APP_CONFIG } from './app';

export const SEO_CONFIG = {
  SITE_URL: APP_CONFIG.APP_DOMAIN,
  SITE_NAME: APP_CONFIG.APP_NAME,
  SITE_DESCRIPTION: APP_CONFIG.APP_DESCRIPTION,
  GOOGLE_SITE_VERIFICATION: import.meta.env.VITE_GOOGLE_SITE_VERIFICATION || '',
};